{
 "title": "Infrastructure & Performance",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Throughput",
   "type": "timeseries",
   "description": " Total requests per second across all endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flashcard_api_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage (Cores)",
   "type": "timeseries",
   "description": "Shows resource usage and helps identify CPU bottlenecks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"apps\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "Average response time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flashcard_api_request_duration_seconds_sum[5m])) / sum(rate(flashcard_api_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (MB)",
   "type": "timeseries",
   "description": "Monitors memory consumption and potential memory leaks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"apps\", container!=\"\"}) by (pod) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Distribution",
   "type": "timeseries",
   "description": "Quickly spot error patterns and client vs server issues",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flashcard_api_requests_total[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}