# Ansible Inventory File
# Auto-generated by Terraform - DO NOT EDIT MANUALLY

# ==========================================================
# Kubernetes Cluster: ${cluster_name}
# ==========================================================

# Control Plane Nodes
[control_plane]
%{ for node in control_plane_nodes ~}
${node.name} ansible_host=${node.ip} ansible_user=${ssh_user} ansible_ssh_common_args='-o StrictHostKeyChecking=no'
%{ endfor ~}

# Worker Nodes
[workers]
%{ for node in worker_nodes ~}
${node.name} ansible_host=${node.ip} ansible_user=${ssh_user} ansible_ssh_common_args='-o StrictHostKeyChecking=no'
%{ endfor ~}

# All Kubernetes Nodes
[k8s_cluster:children]
control_plane
workers

# Variables for all nodes
[k8s_cluster:vars]
ansible_python_interpreter=/usr/bin/python3